In [1]:
import numpy as np
import pandas as pd

In [2]:
# from feature_engine._prediction.target_mean_classifier import TargetMeanClassifier

In [3]:
from feature_engine._prediction.target_mean_regressor import TargetMeanRegressor

In [4]:
def df_regression():
    df = {
        "cat_var_A": ["A"] * 5 + ["B"] * 5 + ["C"] * 5 + ["D"] * 5,
        "cat_var_B": ["A"] * 6 + ["B"] * 2 + ["C"] * 2 + ["B"] * 2 + ["C"] * 2 + ["D"] * 6,
        "num_var_A": [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4],
        "num_var_B": [1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 2, 2, 3, 3, 4, 4, 4, 4, 4, 4],
    }

    df = pd.DataFrame(df)
    y = pd.Series([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])
    return df, y

X, y = df_regression()

X.head()

cat_var_A cat_var_B  num_var_A  num_var_B
0         A         A          1          1
1         A         A          1          1
2         A         A          1          1
3         A         A          1          1
4         A         A          1          1

In [20]:
    tr = TargetMeanRegressor(bins=2)
    tr.fit(X, y)

    pred = tr.predict(X)

In [21]:
pred

array([0.34166667, 0.34166667, 0.34166667, 0.34166667, 0.34166667,
       0.59166667, 0.925     , 0.925     , 1.325     , 1.325     ,
       1.675     , 1.675     , 2.075     , 2.075     , 2.40833333,
       2.65833333, 2.65833333, 2.65833333, 2.65833333, 2.65833333])

In [9]:
np.mean([0, 0, 0, 0, 0, 1])

0.16666666666666666

In [31]:
tr.predict_log_proba(X)

array([[-0.05129329, -2.99573227],
       [-0.05129329, -2.99573227],
       [-0.05129329, -2.99573227],
       [-0.05129329, -2.99573227],
       [-0.05129329, -2.99573227],
       [-0.05129329, -2.99573227],
       [-0.19237189, -1.74296931],
       [-0.19237189, -1.74296931],
       [-0.39304259, -1.1239301 ],
       [-0.39304259, -1.1239301 ],
       [-1.1239301 , -0.39304259],
       [-1.1239301 , -0.39304259],
       [-1.74296931, -0.19237189],
       [-1.74296931, -0.19237189],
       [-2.99573227, -0.05129329],
       [-2.99573227, -0.05129329],
       [-2.99573227, -0.05129329],
       [-2.99573227, -0.05129329],
       [-2.99573227, -0.05129329],
       [-2.99573227, -0.05129329]])

In [11]:
isinstance(prob, np.ndarray)

True

In [13]:
arr = np.array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]]              )

In [14]:
arr

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [15]:
np.array_equal(arr,prob)

True